version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    environment:
      DB_PASSWORD: ${DB_PASSWORD}  # Ensure this matches the MySQL user password
    networks:
      - backend-network
    depends_on:
      - db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend-network
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge

volumes:
  db_data: